CREATE TABLE SupportTickets (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Status VARCHAR(20) NOT NULL,
    Category VARCHAR(20) NOT NULL,
    Closed_At DATETIME,
    Created_At DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME,
    Client_Id BINARY(16) NOT NULL,
    Agent_Id BINARY(16),

    FOREIGN KEY (Client_Id) REFERENCES Clients(Id),
    FOREIGN KEY (Agent_Id) REFERENCES Agents(Id)
);