CREATE TABLE Feedbacks (
    Id BIGSERIAL PRIMARY KEY,
    Comments TEXT NOT NULL,
    Rating INT NOT NULL,
    Created_At TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP,
    Support_Ticket_Id BIGINT,

    FOREIGN KEY (Support_Ticket_Id) REFERENCES SupportTickets(Id) ON DELETE CASCADE
);
