ALTER TABLE Feedbacks
ADD CONSTRAINT FK_SupportTicketId
FOREIGN KEY (SupportTicketId) REFERENCES SupportTickets(Id) ON DELETE CASCADE;

ALTER TABLE SupportTickets
ADD CONSTRAINT FK_ClientId
FOREIGN KEY (ClientId) REFERENCES Clients(Id);

ALTER TABLE SupportTickets
ADD CONSTRAINT FK_AgentId
FOREIGN KEY (AgentId) REFERENCES Agents(Id);
